variables:
  REMOTE_ADDRESS: $REMOTE_USER@$REMOTE_HOST
  ENVIRONMENT: stage

stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        ENVIRONMENT: stage
    - if: $CI_COMMIT_BRANCH == "prod"
      variables:
        ENVIRONMENT: prod
    - if: $CI_COMMIT_BRANCH == "stage"
      variables:
        ENVIRONMENT: qa-stage
    - when: always

stage_build:
  stage: build
  environment: $ENVIRONMENT
  tags:
    - web
  script:
    - echo "$ENV" > ".env"
    - yarn install
    - yarn build

  artifacts:
    name: $CI_PROJECT_NAME
    expire_in: 1 week
    paths:
      - dist/

stage_deploy:
  stage: deploy
  environment: $ENVIRONMENT
  rules:
    - if: $CI_COMMIT_BRANCH == "prod"
      when: manual
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_COMMIT_BRANCH == "stage"
      when: always
  tags:
    - web
  script:
    - rsync -avh ./dist/* $REMOTE_ADDRESS:$REMOTE_DIR --delete